/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OrderConfirmedOrderIdRouteImport } from './routes/order-confirmed.$orderId'
import { Route as AdminTickerRouteImport } from './routes/admin/ticker'
import { Route as AdminThemeRouteImport } from './routes/admin/theme'
import { Route as AdminSubscribersRouteImport } from './routes/admin/subscribers'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminPopupRouteImport } from './routes/admin/popup'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminHomepageRouteImport } from './routes/admin/homepage'
import { Route as AdminHeaderRouteImport } from './routes/admin/header'
import { Route as AdminFooterRouteImport } from './routes/admin/footer'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'

const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OrderConfirmedOrderIdRoute = OrderConfirmedOrderIdRouteImport.update({
  id: '/order-confirmed/$orderId',
  path: '/order-confirmed/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTickerRoute = AdminTickerRouteImport.update({
  id: '/ticker',
  path: '/ticker',
  getParentRoute: () => AdminRoute,
} as any)
const AdminThemeRoute = AdminThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPopupRoute = AdminPopupRouteImport.update({
  id: '/popup',
  path: '/popup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeaderRoute = AdminHeaderRouteImport.update({
  id: '/header',
  path: '/header',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFooterRoute = AdminFooterRouteImport.update({
  id: '/footer',
  path: '/footer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/header': typeof AdminHeaderRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/popup': typeof AdminPopupRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/ticker': typeof AdminTickerRoute
  '/order-confirmed/$orderId': typeof OrderConfirmedOrderIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/header': typeof AdminHeaderRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/popup': typeof AdminPopupRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/ticker': typeof AdminTickerRoute
  '/order-confirmed/$orderId': typeof OrderConfirmedOrderIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/header': typeof AdminHeaderRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/popup': typeof AdminPopupRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/ticker': typeof AdminTickerRoute
  '/order-confirmed/$orderId': typeof OrderConfirmedOrderIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/admin/categories'
    | '/admin/footer'
    | '/admin/header'
    | '/admin/homepage'
    | '/admin/orders'
    | '/admin/popup'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/theme'
    | '/admin/ticker'
    | '/order-confirmed/$orderId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/admin/categories'
    | '/admin/footer'
    | '/admin/header'
    | '/admin/homepage'
    | '/admin/orders'
    | '/admin/popup'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/theme'
    | '/admin/ticker'
    | '/order-confirmed/$orderId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/admin/categories'
    | '/admin/footer'
    | '/admin/header'
    | '/admin/homepage'
    | '/admin/orders'
    | '/admin/popup'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/theme'
    | '/admin/ticker'
    | '/order-confirmed/$orderId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  OrderConfirmedOrderIdRoute: typeof OrderConfirmedOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/order-confirmed/$orderId': {
      id: '/order-confirmed/$orderId'
      path: '/order-confirmed/$orderId'
      fullPath: '/order-confirmed/$orderId'
      preLoaderRoute: typeof OrderConfirmedOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ticker': {
      id: '/admin/ticker'
      path: '/ticker'
      fullPath: '/admin/ticker'
      preLoaderRoute: typeof AdminTickerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/theme': {
      id: '/admin/theme'
      path: '/theme'
      fullPath: '/admin/theme'
      preLoaderRoute: typeof AdminThemeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/popup': {
      id: '/admin/popup'
      path: '/popup'
      fullPath: '/admin/popup'
      preLoaderRoute: typeof AdminPopupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/header': {
      id: '/admin/header'
      path: '/header'
      fullPath: '/admin/header'
      preLoaderRoute: typeof AdminHeaderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/footer': {
      id: '/admin/footer'
      path: '/footer'
      fullPath: '/admin/footer'
      preLoaderRoute: typeof AdminFooterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminFooterRoute: typeof AdminFooterRoute
  AdminHeaderRoute: typeof AdminHeaderRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPopupRoute: typeof AdminPopupRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminThemeRoute: typeof AdminThemeRoute
  AdminTickerRoute: typeof AdminTickerRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminFooterRoute: AdminFooterRoute,
  AdminHeaderRoute: AdminHeaderRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPopupRoute: AdminPopupRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminThemeRoute: AdminThemeRoute,
  AdminTickerRoute: AdminTickerRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  OrderConfirmedOrderIdRoute: OrderConfirmedOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
