/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as ProdusSlugRouteImport } from './routes/produs.$slug'
import { Route as PageSlugRouteImport } from './routes/page.$slug'
import { Route as OrderConfirmedOrderIdRouteImport } from './routes/order-confirmed.$orderId'
import { Route as CategorieSlugRouteImport } from './routes/categorie.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTransactionsRouteImport } from './routes/admin/transactions'
import { Route as AdminTrackingRouteImport } from './routes/admin/tracking'
import { Route as AdminTicketsRouteImport } from './routes/admin/tickets'
import { Route as AdminTickerRouteImport } from './routes/admin/ticker'
import { Route as AdminThemeRouteImport } from './routes/admin/theme'
import { Route as AdminSystemRouteImport } from './routes/admin/system'
import { Route as AdminSubscribersRouteImport } from './routes/admin/subscribers'
import { Route as AdminStockRouteImport } from './routes/admin/stock'
import { Route as AdminSocialProofRouteImport } from './routes/admin/social-proof'
import { Route as AdminShippingRouteImport } from './routes/admin/shipping'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminReturnsRouteImport } from './routes/admin/returns'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminPopupRouteImport } from './routes/admin/popup'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminPagesRouteImport } from './routes/admin/pages'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminIntegrationsRouteImport } from './routes/admin/integrations'
import { Route as AdminHomepageRouteImport } from './routes/admin/homepage'
import { Route as AdminHeaderRouteImport } from './routes/admin/header'
import { Route as AdminFooterRouteImport } from './routes/admin/footer'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminCrmRouteImport } from './routes/admin/crm'
import { Route as AdminCouponsRouteImport } from './routes/admin/coupons'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'
import { Route as AdminAiRouteImport } from './routes/admin/ai'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AdminAbandonedCartsRouteImport } from './routes/admin/abandoned-carts'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as AccountOrdersRouteImport } from './routes/account/orders'
import { Route as AccountFavoritesRouteImport } from './routes/account/favorites'
import { Route as AccountAddressesRouteImport } from './routes/account/addresses'
import { Route as AdminStockWarehousesRouteImport } from './routes/admin/stock.warehouses'
import { Route as AdminStockTransfersRouteImport } from './routes/admin/stock.transfers'
import { Route as AdminStockSuppliersRouteImport } from './routes/admin/stock.suppliers'
import { Route as AdminStockPurchaseOrdersRouteImport } from './routes/admin/stock.purchase-orders'
import { Route as AdminStockMovementsRouteImport } from './routes/admin/stock.movements'
import { Route as AdminStockManagerRouteImport } from './routes/admin/stock.manager'
import { Route as AdminStockBatchesRouteImport } from './routes/admin/stock.batches'
import { Route as AdminStockAlertsRouteImport } from './routes/admin/stock.alerts'
import { Route as AdminSettingsCheckoutRouteImport } from './routes/admin/settings.checkout'
import { Route as AdminReportsTopProductsRouteImport } from './routes/admin/reports.top-products'
import { Route as AdminReportsProfitRouteImport } from './routes/admin/reports.profit'
import { Route as AdminReportsCustomersRouteImport } from './routes/admin/reports.customers'
import { Route as AdminReportsConversionRouteImport } from './routes/admin/reports.conversion'
import { Route as AdminContentSeoRouteImport } from './routes/admin/content.seo'
import { Route as AdminContentRedirectsRouteImport } from './routes/admin/content.redirects'
import { Route as AdminContentFaqRouteImport } from './routes/admin/content.faq'
import { Route as AdminContentEmailTemplatesRouteImport } from './routes/admin/content.email-templates'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const ProdusSlugRoute = ProdusSlugRouteImport.update({
  id: '/produs/$slug',
  path: '/produs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PageSlugRoute = PageSlugRouteImport.update({
  id: '/page/$slug',
  path: '/page/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedOrderIdRoute = OrderConfirmedOrderIdRouteImport.update({
  id: '/order-confirmed/$orderId',
  path: '/order-confirmed/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorieSlugRoute = CategorieSlugRouteImport.update({
  id: '/categorie/$slug',
  path: '/categorie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrackingRoute = AdminTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTickerRoute = AdminTickerRouteImport.update({
  id: '/ticker',
  path: '/ticker',
  getParentRoute: () => AdminRoute,
} as any)
const AdminThemeRoute = AdminThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStockRoute = AdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSocialProofRoute = AdminSocialProofRouteImport.update({
  id: '/social-proof',
  path: '/social-proof',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReturnsRoute = AdminReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPopupRoute = AdminPopupRouteImport.update({
  id: '/popup',
  path: '/popup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeaderRoute = AdminHeaderRouteImport.update({
  id: '/header',
  path: '/header',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFooterRoute = AdminFooterRouteImport.update({
  id: '/footer',
  path: '/footer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmRoute = AdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbandonedCartsRoute = AdminAbandonedCartsRouteImport.update({
  id: '/abandoned-carts',
  path: '/abandoned-carts',
  getParentRoute: () => AdminRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountFavoritesRoute = AccountFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const AdminStockWarehousesRoute = AdminStockWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AdminStockRoute,
} as any)
const AdminStockTransfersRoute = AdminStockTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AdminStockRoute,
} as any)
const AdminStockSuppliersRoute = AdminStockSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminStockRoute,
} as any)
const AdminStockPurchaseOrdersRoute =
  AdminStockPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AdminStockRoute,
  } as any)
const AdminStockMovementsRoute = AdminStockMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AdminStockRoute,
} as any)
const AdminStockManagerRoute = AdminStockManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AdminStockRoute,
} as any)
const AdminStockBatchesRoute = AdminStockBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AdminStockRoute,
} as any)
const AdminStockAlertsRoute = AdminStockAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminStockRoute,
} as any)
const AdminSettingsCheckoutRoute = AdminSettingsCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminReportsTopProductsRoute = AdminReportsTopProductsRouteImport.update({
  id: '/top-products',
  path: '/top-products',
  getParentRoute: () => AdminReportsRoute,
} as any)
const AdminReportsProfitRoute = AdminReportsProfitRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => AdminReportsRoute,
} as any)
const AdminReportsCustomersRoute = AdminReportsCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminReportsRoute,
} as any)
const AdminReportsConversionRoute = AdminReportsConversionRouteImport.update({
  id: '/conversion',
  path: '/conversion',
  getParentRoute: () => AdminReportsRoute,
} as any)
const AdminContentSeoRoute = AdminContentSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminContentRoute,
} as any)
const AdminContentRedirectsRoute = AdminContentRedirectsRouteImport.update({
  id: '/redirects',
  path: '/redirects',
  getParentRoute: () => AdminContentRoute,
} as any)
const AdminContentFaqRoute = AdminContentFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminContentRoute,
} as any)
const AdminContentEmailTemplatesRoute =
  AdminContentEmailTemplatesRouteImport.update({
    id: '/email-templates',
    path: '/email-templates',
    getParentRoute: () => AdminContentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/settings': typeof AccountSettingsRoute
  '/admin/abandoned-carts': typeof AdminAbandonedCartsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRouteWithChildren
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/header': typeof AdminHeaderRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/popup': typeof AdminPopupRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRouteWithChildren
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/social-proof': typeof AdminSocialProofRoute
  '/admin/stock': typeof AdminStockRouteWithChildren
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/ticker': typeof AdminTickerRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/tracking': typeof AdminTrackingRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/order-confirmed/$orderId': typeof OrderConfirmedOrderIdRoute
  '/page/$slug': typeof PageSlugRoute
  '/produs/$slug': typeof ProdusSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/content/email-templates': typeof AdminContentEmailTemplatesRoute
  '/admin/content/faq': typeof AdminContentFaqRoute
  '/admin/content/redirects': typeof AdminContentRedirectsRoute
  '/admin/content/seo': typeof AdminContentSeoRoute
  '/admin/reports/conversion': typeof AdminReportsConversionRoute
  '/admin/reports/customers': typeof AdminReportsCustomersRoute
  '/admin/reports/profit': typeof AdminReportsProfitRoute
  '/admin/reports/top-products': typeof AdminReportsTopProductsRoute
  '/admin/settings/checkout': typeof AdminSettingsCheckoutRoute
  '/admin/stock/alerts': typeof AdminStockAlertsRoute
  '/admin/stock/batches': typeof AdminStockBatchesRoute
  '/admin/stock/manager': typeof AdminStockManagerRoute
  '/admin/stock/movements': typeof AdminStockMovementsRoute
  '/admin/stock/purchase-orders': typeof AdminStockPurchaseOrdersRoute
  '/admin/stock/suppliers': typeof AdminStockSuppliersRoute
  '/admin/stock/transfers': typeof AdminStockTransfersRoute
  '/admin/stock/warehouses': typeof AdminStockWarehousesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/settings': typeof AccountSettingsRoute
  '/admin/abandoned-carts': typeof AdminAbandonedCartsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRouteWithChildren
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/header': typeof AdminHeaderRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/popup': typeof AdminPopupRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRouteWithChildren
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/social-proof': typeof AdminSocialProofRoute
  '/admin/stock': typeof AdminStockRouteWithChildren
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/ticker': typeof AdminTickerRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/tracking': typeof AdminTrackingRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/order-confirmed/$orderId': typeof OrderConfirmedOrderIdRoute
  '/page/$slug': typeof PageSlugRoute
  '/produs/$slug': typeof ProdusSlugRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/content/email-templates': typeof AdminContentEmailTemplatesRoute
  '/admin/content/faq': typeof AdminContentFaqRoute
  '/admin/content/redirects': typeof AdminContentRedirectsRoute
  '/admin/content/seo': typeof AdminContentSeoRoute
  '/admin/reports/conversion': typeof AdminReportsConversionRoute
  '/admin/reports/customers': typeof AdminReportsCustomersRoute
  '/admin/reports/profit': typeof AdminReportsProfitRoute
  '/admin/reports/top-products': typeof AdminReportsTopProductsRoute
  '/admin/settings/checkout': typeof AdminSettingsCheckoutRoute
  '/admin/stock/alerts': typeof AdminStockAlertsRoute
  '/admin/stock/batches': typeof AdminStockBatchesRoute
  '/admin/stock/manager': typeof AdminStockManagerRoute
  '/admin/stock/movements': typeof AdminStockMovementsRoute
  '/admin/stock/purchase-orders': typeof AdminStockPurchaseOrdersRoute
  '/admin/stock/suppliers': typeof AdminStockSuppliersRoute
  '/admin/stock/transfers': typeof AdminStockTransfersRoute
  '/admin/stock/warehouses': typeof AdminStockWarehousesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/settings': typeof AccountSettingsRoute
  '/admin/abandoned-carts': typeof AdminAbandonedCartsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRouteWithChildren
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/header': typeof AdminHeaderRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/popup': typeof AdminPopupRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRouteWithChildren
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/social-proof': typeof AdminSocialProofRoute
  '/admin/stock': typeof AdminStockRouteWithChildren
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/ticker': typeof AdminTickerRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/tracking': typeof AdminTrackingRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/order-confirmed/$orderId': typeof OrderConfirmedOrderIdRoute
  '/page/$slug': typeof PageSlugRoute
  '/produs/$slug': typeof ProdusSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/content/email-templates': typeof AdminContentEmailTemplatesRoute
  '/admin/content/faq': typeof AdminContentFaqRoute
  '/admin/content/redirects': typeof AdminContentRedirectsRoute
  '/admin/content/seo': typeof AdminContentSeoRoute
  '/admin/reports/conversion': typeof AdminReportsConversionRoute
  '/admin/reports/customers': typeof AdminReportsCustomersRoute
  '/admin/reports/profit': typeof AdminReportsProfitRoute
  '/admin/reports/top-products': typeof AdminReportsTopProductsRoute
  '/admin/settings/checkout': typeof AdminSettingsCheckoutRoute
  '/admin/stock/alerts': typeof AdminStockAlertsRoute
  '/admin/stock/batches': typeof AdminStockBatchesRoute
  '/admin/stock/manager': typeof AdminStockManagerRoute
  '/admin/stock/movements': typeof AdminStockMovementsRoute
  '/admin/stock/purchase-orders': typeof AdminStockPurchaseOrdersRoute
  '/admin/stock/suppliers': typeof AdminStockSuppliersRoute
  '/admin/stock/transfers': typeof AdminStockTransfersRoute
  '/admin/stock/warehouses': typeof AdminStockWarehousesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/compare'
    | '/forgot-password'
    | '/reset-password'
    | '/track-order'
    | '/wishlist'
    | '/account/addresses'
    | '/account/favorites'
    | '/account/orders'
    | '/account/settings'
    | '/admin/abandoned-carts'
    | '/admin/activity'
    | '/admin/ai'
    | '/admin/blog'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/crm'
    | '/admin/customers'
    | '/admin/footer'
    | '/admin/header'
    | '/admin/homepage'
    | '/admin/integrations'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/popup'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/returns'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/social-proof'
    | '/admin/stock'
    | '/admin/subscribers'
    | '/admin/system'
    | '/admin/theme'
    | '/admin/ticker'
    | '/admin/tickets'
    | '/admin/tracking'
    | '/admin/transactions'
    | '/admin/users'
    | '/blog/$slug'
    | '/categorie/$slug'
    | '/order-confirmed/$orderId'
    | '/page/$slug'
    | '/produs/$slug'
    | '/account/'
    | '/admin/'
    | '/admin/content/email-templates'
    | '/admin/content/faq'
    | '/admin/content/redirects'
    | '/admin/content/seo'
    | '/admin/reports/conversion'
    | '/admin/reports/customers'
    | '/admin/reports/profit'
    | '/admin/reports/top-products'
    | '/admin/settings/checkout'
    | '/admin/stock/alerts'
    | '/admin/stock/batches'
    | '/admin/stock/manager'
    | '/admin/stock/movements'
    | '/admin/stock/purchase-orders'
    | '/admin/stock/suppliers'
    | '/admin/stock/transfers'
    | '/admin/stock/warehouses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/compare'
    | '/forgot-password'
    | '/reset-password'
    | '/track-order'
    | '/wishlist'
    | '/account/addresses'
    | '/account/favorites'
    | '/account/orders'
    | '/account/settings'
    | '/admin/abandoned-carts'
    | '/admin/activity'
    | '/admin/ai'
    | '/admin/blog'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/crm'
    | '/admin/customers'
    | '/admin/footer'
    | '/admin/header'
    | '/admin/homepage'
    | '/admin/integrations'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/popup'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/returns'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/social-proof'
    | '/admin/stock'
    | '/admin/subscribers'
    | '/admin/system'
    | '/admin/theme'
    | '/admin/ticker'
    | '/admin/tickets'
    | '/admin/tracking'
    | '/admin/transactions'
    | '/admin/users'
    | '/blog/$slug'
    | '/categorie/$slug'
    | '/order-confirmed/$orderId'
    | '/page/$slug'
    | '/produs/$slug'
    | '/account'
    | '/admin'
    | '/admin/content/email-templates'
    | '/admin/content/faq'
    | '/admin/content/redirects'
    | '/admin/content/seo'
    | '/admin/reports/conversion'
    | '/admin/reports/customers'
    | '/admin/reports/profit'
    | '/admin/reports/top-products'
    | '/admin/settings/checkout'
    | '/admin/stock/alerts'
    | '/admin/stock/batches'
    | '/admin/stock/manager'
    | '/admin/stock/movements'
    | '/admin/stock/purchase-orders'
    | '/admin/stock/suppliers'
    | '/admin/stock/transfers'
    | '/admin/stock/warehouses'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/compare'
    | '/forgot-password'
    | '/reset-password'
    | '/track-order'
    | '/wishlist'
    | '/account/addresses'
    | '/account/favorites'
    | '/account/orders'
    | '/account/settings'
    | '/admin/abandoned-carts'
    | '/admin/activity'
    | '/admin/ai'
    | '/admin/blog'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/crm'
    | '/admin/customers'
    | '/admin/footer'
    | '/admin/header'
    | '/admin/homepage'
    | '/admin/integrations'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/popup'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/returns'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/social-proof'
    | '/admin/stock'
    | '/admin/subscribers'
    | '/admin/system'
    | '/admin/theme'
    | '/admin/ticker'
    | '/admin/tickets'
    | '/admin/tracking'
    | '/admin/transactions'
    | '/admin/users'
    | '/blog/$slug'
    | '/categorie/$slug'
    | '/order-confirmed/$orderId'
    | '/page/$slug'
    | '/produs/$slug'
    | '/account/'
    | '/admin/'
    | '/admin/content/email-templates'
    | '/admin/content/faq'
    | '/admin/content/redirects'
    | '/admin/content/seo'
    | '/admin/reports/conversion'
    | '/admin/reports/customers'
    | '/admin/reports/profit'
    | '/admin/reports/top-products'
    | '/admin/settings/checkout'
    | '/admin/stock/alerts'
    | '/admin/stock/batches'
    | '/admin/stock/manager'
    | '/admin/stock/movements'
    | '/admin/stock/purchase-orders'
    | '/admin/stock/suppliers'
    | '/admin/stock/transfers'
    | '/admin/stock/warehouses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CartRoute: typeof CartRoute
  CatalogRoute: typeof CatalogRoute
  CheckoutRoute: typeof CheckoutRoute
  CompareRoute: typeof CompareRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TrackOrderRoute: typeof TrackOrderRoute
  WishlistRoute: typeof WishlistRoute
  CategorieSlugRoute: typeof CategorieSlugRoute
  OrderConfirmedOrderIdRoute: typeof OrderConfirmedOrderIdRoute
  PageSlugRoute: typeof PageSlugRoute
  ProdusSlugRoute: typeof ProdusSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/produs/$slug': {
      id: '/produs/$slug'
      path: '/produs/$slug'
      fullPath: '/produs/$slug'
      preLoaderRoute: typeof ProdusSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/$slug': {
      id: '/page/$slug'
      path: '/page/$slug'
      fullPath: '/page/$slug'
      preLoaderRoute: typeof PageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed/$orderId': {
      id: '/order-confirmed/$orderId'
      path: '/order-confirmed/$orderId'
      fullPath: '/order-confirmed/$orderId'
      preLoaderRoute: typeof OrderConfirmedOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorie/$slug': {
      id: '/categorie/$slug'
      path: '/categorie/$slug'
      fullPath: '/categorie/$slug'
      preLoaderRoute: typeof CategorieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tracking': {
      id: '/admin/tracking'
      path: '/tracking'
      fullPath: '/admin/tracking'
      preLoaderRoute: typeof AdminTrackingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ticker': {
      id: '/admin/ticker'
      path: '/ticker'
      fullPath: '/admin/ticker'
      preLoaderRoute: typeof AdminTickerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/theme': {
      id: '/admin/theme'
      path: '/theme'
      fullPath: '/admin/theme'
      preLoaderRoute: typeof AdminThemeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stock': {
      id: '/admin/stock'
      path: '/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AdminStockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/social-proof': {
      id: '/admin/social-proof'
      path: '/social-proof'
      fullPath: '/admin/social-proof'
      preLoaderRoute: typeof AdminSocialProofRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/returns': {
      id: '/admin/returns'
      path: '/returns'
      fullPath: '/admin/returns'
      preLoaderRoute: typeof AdminReturnsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/popup': {
      id: '/admin/popup'
      path: '/popup'
      fullPath: '/admin/popup'
      preLoaderRoute: typeof AdminPopupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/header': {
      id: '/admin/header'
      path: '/header'
      fullPath: '/admin/header'
      preLoaderRoute: typeof AdminHeaderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/footer': {
      id: '/admin/footer'
      path: '/footer'
      fullPath: '/admin/footer'
      preLoaderRoute: typeof AdminFooterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm': {
      id: '/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AdminCrmRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/abandoned-carts': {
      id: '/admin/abandoned-carts'
      path: '/abandoned-carts'
      fullPath: '/admin/abandoned-carts'
      preLoaderRoute: typeof AdminAbandonedCartsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/favorites': {
      id: '/account/favorites'
      path: '/favorites'
      fullPath: '/account/favorites'
      preLoaderRoute: typeof AccountFavoritesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/stock/warehouses': {
      id: '/admin/stock/warehouses'
      path: '/warehouses'
      fullPath: '/admin/stock/warehouses'
      preLoaderRoute: typeof AdminStockWarehousesRouteImport
      parentRoute: typeof AdminStockRoute
    }
    '/admin/stock/transfers': {
      id: '/admin/stock/transfers'
      path: '/transfers'
      fullPath: '/admin/stock/transfers'
      preLoaderRoute: typeof AdminStockTransfersRouteImport
      parentRoute: typeof AdminStockRoute
    }
    '/admin/stock/suppliers': {
      id: '/admin/stock/suppliers'
      path: '/suppliers'
      fullPath: '/admin/stock/suppliers'
      preLoaderRoute: typeof AdminStockSuppliersRouteImport
      parentRoute: typeof AdminStockRoute
    }
    '/admin/stock/purchase-orders': {
      id: '/admin/stock/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/admin/stock/purchase-orders'
      preLoaderRoute: typeof AdminStockPurchaseOrdersRouteImport
      parentRoute: typeof AdminStockRoute
    }
    '/admin/stock/movements': {
      id: '/admin/stock/movements'
      path: '/movements'
      fullPath: '/admin/stock/movements'
      preLoaderRoute: typeof AdminStockMovementsRouteImport
      parentRoute: typeof AdminStockRoute
    }
    '/admin/stock/manager': {
      id: '/admin/stock/manager'
      path: '/manager'
      fullPath: '/admin/stock/manager'
      preLoaderRoute: typeof AdminStockManagerRouteImport
      parentRoute: typeof AdminStockRoute
    }
    '/admin/stock/batches': {
      id: '/admin/stock/batches'
      path: '/batches'
      fullPath: '/admin/stock/batches'
      preLoaderRoute: typeof AdminStockBatchesRouteImport
      parentRoute: typeof AdminStockRoute
    }
    '/admin/stock/alerts': {
      id: '/admin/stock/alerts'
      path: '/alerts'
      fullPath: '/admin/stock/alerts'
      preLoaderRoute: typeof AdminStockAlertsRouteImport
      parentRoute: typeof AdminStockRoute
    }
    '/admin/settings/checkout': {
      id: '/admin/settings/checkout'
      path: '/checkout'
      fullPath: '/admin/settings/checkout'
      preLoaderRoute: typeof AdminSettingsCheckoutRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/reports/top-products': {
      id: '/admin/reports/top-products'
      path: '/top-products'
      fullPath: '/admin/reports/top-products'
      preLoaderRoute: typeof AdminReportsTopProductsRouteImport
      parentRoute: typeof AdminReportsRoute
    }
    '/admin/reports/profit': {
      id: '/admin/reports/profit'
      path: '/profit'
      fullPath: '/admin/reports/profit'
      preLoaderRoute: typeof AdminReportsProfitRouteImport
      parentRoute: typeof AdminReportsRoute
    }
    '/admin/reports/customers': {
      id: '/admin/reports/customers'
      path: '/customers'
      fullPath: '/admin/reports/customers'
      preLoaderRoute: typeof AdminReportsCustomersRouteImport
      parentRoute: typeof AdminReportsRoute
    }
    '/admin/reports/conversion': {
      id: '/admin/reports/conversion'
      path: '/conversion'
      fullPath: '/admin/reports/conversion'
      preLoaderRoute: typeof AdminReportsConversionRouteImport
      parentRoute: typeof AdminReportsRoute
    }
    '/admin/content/seo': {
      id: '/admin/content/seo'
      path: '/seo'
      fullPath: '/admin/content/seo'
      preLoaderRoute: typeof AdminContentSeoRouteImport
      parentRoute: typeof AdminContentRoute
    }
    '/admin/content/redirects': {
      id: '/admin/content/redirects'
      path: '/redirects'
      fullPath: '/admin/content/redirects'
      preLoaderRoute: typeof AdminContentRedirectsRouteImport
      parentRoute: typeof AdminContentRoute
    }
    '/admin/content/faq': {
      id: '/admin/content/faq'
      path: '/faq'
      fullPath: '/admin/content/faq'
      preLoaderRoute: typeof AdminContentFaqRouteImport
      parentRoute: typeof AdminContentRoute
    }
    '/admin/content/email-templates': {
      id: '/admin/content/email-templates'
      path: '/email-templates'
      fullPath: '/admin/content/email-templates'
      preLoaderRoute: typeof AdminContentEmailTemplatesRouteImport
      parentRoute: typeof AdminContentRoute
    }
  }
}

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountFavoritesRoute: typeof AccountFavoritesRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountFavoritesRoute: AccountFavoritesRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminContentRouteChildren {
  AdminContentEmailTemplatesRoute: typeof AdminContentEmailTemplatesRoute
  AdminContentFaqRoute: typeof AdminContentFaqRoute
  AdminContentRedirectsRoute: typeof AdminContentRedirectsRoute
  AdminContentSeoRoute: typeof AdminContentSeoRoute
}

const AdminContentRouteChildren: AdminContentRouteChildren = {
  AdminContentEmailTemplatesRoute: AdminContentEmailTemplatesRoute,
  AdminContentFaqRoute: AdminContentFaqRoute,
  AdminContentRedirectsRoute: AdminContentRedirectsRoute,
  AdminContentSeoRoute: AdminContentSeoRoute,
}

const AdminContentRouteWithChildren = AdminContentRoute._addFileChildren(
  AdminContentRouteChildren,
)

interface AdminReportsRouteChildren {
  AdminReportsConversionRoute: typeof AdminReportsConversionRoute
  AdminReportsCustomersRoute: typeof AdminReportsCustomersRoute
  AdminReportsProfitRoute: typeof AdminReportsProfitRoute
  AdminReportsTopProductsRoute: typeof AdminReportsTopProductsRoute
}

const AdminReportsRouteChildren: AdminReportsRouteChildren = {
  AdminReportsConversionRoute: AdminReportsConversionRoute,
  AdminReportsCustomersRoute: AdminReportsCustomersRoute,
  AdminReportsProfitRoute: AdminReportsProfitRoute,
  AdminReportsTopProductsRoute: AdminReportsTopProductsRoute,
}

const AdminReportsRouteWithChildren = AdminReportsRoute._addFileChildren(
  AdminReportsRouteChildren,
)

interface AdminSettingsRouteChildren {
  AdminSettingsCheckoutRoute: typeof AdminSettingsCheckoutRoute
}

const AdminSettingsRouteChildren: AdminSettingsRouteChildren = {
  AdminSettingsCheckoutRoute: AdminSettingsCheckoutRoute,
}

const AdminSettingsRouteWithChildren = AdminSettingsRoute._addFileChildren(
  AdminSettingsRouteChildren,
)

interface AdminStockRouteChildren {
  AdminStockAlertsRoute: typeof AdminStockAlertsRoute
  AdminStockBatchesRoute: typeof AdminStockBatchesRoute
  AdminStockManagerRoute: typeof AdminStockManagerRoute
  AdminStockMovementsRoute: typeof AdminStockMovementsRoute
  AdminStockPurchaseOrdersRoute: typeof AdminStockPurchaseOrdersRoute
  AdminStockSuppliersRoute: typeof AdminStockSuppliersRoute
  AdminStockTransfersRoute: typeof AdminStockTransfersRoute
  AdminStockWarehousesRoute: typeof AdminStockWarehousesRoute
}

const AdminStockRouteChildren: AdminStockRouteChildren = {
  AdminStockAlertsRoute: AdminStockAlertsRoute,
  AdminStockBatchesRoute: AdminStockBatchesRoute,
  AdminStockManagerRoute: AdminStockManagerRoute,
  AdminStockMovementsRoute: AdminStockMovementsRoute,
  AdminStockPurchaseOrdersRoute: AdminStockPurchaseOrdersRoute,
  AdminStockSuppliersRoute: AdminStockSuppliersRoute,
  AdminStockTransfersRoute: AdminStockTransfersRoute,
  AdminStockWarehousesRoute: AdminStockWarehousesRoute,
}

const AdminStockRouteWithChildren = AdminStockRoute._addFileChildren(
  AdminStockRouteChildren,
)

interface AdminRouteChildren {
  AdminAbandonedCartsRoute: typeof AdminAbandonedCartsRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAiRoute: typeof AdminAiRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminContentRoute: typeof AdminContentRouteWithChildren
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCrmRoute: typeof AdminCrmRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminFooterRoute: typeof AdminFooterRoute
  AdminHeaderRoute: typeof AdminHeaderRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPopupRoute: typeof AdminPopupRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRouteWithChildren
  AdminReturnsRoute: typeof AdminReturnsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRouteWithChildren
  AdminShippingRoute: typeof AdminShippingRoute
  AdminSocialProofRoute: typeof AdminSocialProofRoute
  AdminStockRoute: typeof AdminStockRouteWithChildren
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminThemeRoute: typeof AdminThemeRoute
  AdminTickerRoute: typeof AdminTickerRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminTrackingRoute: typeof AdminTrackingRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAbandonedCartsRoute: AdminAbandonedCartsRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminAiRoute: AdminAiRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminContentRoute: AdminContentRouteWithChildren,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCrmRoute: AdminCrmRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminFooterRoute: AdminFooterRoute,
  AdminHeaderRoute: AdminHeaderRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPopupRoute: AdminPopupRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRouteWithChildren,
  AdminReturnsRoute: AdminReturnsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRouteWithChildren,
  AdminShippingRoute: AdminShippingRoute,
  AdminSocialProofRoute: AdminSocialProofRoute,
  AdminStockRoute: AdminStockRouteWithChildren,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminThemeRoute: AdminThemeRoute,
  AdminTickerRoute: AdminTickerRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminTrackingRoute: AdminTrackingRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CartRoute: CartRoute,
  CatalogRoute: CatalogRoute,
  CheckoutRoute: CheckoutRoute,
  CompareRoute: CompareRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TrackOrderRoute: TrackOrderRoute,
  WishlistRoute: WishlistRoute,
  CategorieSlugRoute: CategorieSlugRoute,
  OrderConfirmedOrderIdRoute: OrderConfirmedOrderIdRoute,
  PageSlugRoute: PageSlugRoute,
  ProdusSlugRoute: ProdusSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
